# Generated by Django 3.1.6 on 2021-03-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=20)),
                ('lines', models.IntegerField(default=0)),
            ],
        ),
    ]
