# Generated by Django 3.1.6 on 2021-03-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='file_name',
            field=models.CharField(default='example.ext', max_length=50),
            preserve_default=False,
        ),
    ]
