# Generated by Django 3.1.6 on 2021-04-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_images',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_images',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product_images',
            name='image_number',
            field=models.IntegerField(default=0),
        ),
    ]
