# Generated by Django 3.1.6 on 2021-04-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_auto_20210412_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_images',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product_images',
        ),
    ]
