# Generated by Django 3.1.6 on 2021-04-12 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_auto_20210412_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('direction', models.CharField(max_length=50)),
                ('precautions', models.CharField(max_length=50)),
                ('available', models.IntegerField(default=0)),
                ('total_images', models.IntegerField(default=0)),
                ('manufacturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Product_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('image_number', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.product_class'),
        ),
    ]
