# Generated by Django 3.1.6 on 2021-04-12 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_auto_20210412_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='products_bought',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='total_products',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Product_class',
        ),
        migrations.AddField(
            model_name='product_instance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.product'),
        ),
    ]
