# Generated by Django 3.1.6 on 2021-04-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_auto_20210412_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='products_bought',
        ),
        migrations.AddField(
            model_name='product_instance',
            name='instance_number',
            field=models.IntegerField(default=-1),
        ),
    ]
