# Generated by Django 3.1.6 on 2021-04-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_auto_20210412_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_offset',
            field=models.IntegerField(default=0),
        ),
    ]
