# Generated by Django 3.1.6 on 2021-04-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_auto_20210412_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_products',
            new_name='quantity',
        ),
    ]
