# Generated by Django 3.1.6 on 2021-04-12 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_auto_20210412_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_bill',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.customer'),
        ),
    ]
