# Generated by Django 3.1.6 on 2021-04-14 10:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_order_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_sold',
            new_name='sold',
        ),
        migrations.RenameField(
            model_name='product_images',
            old_name='image_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='product_instance',
            old_name='instance_number',
            new_name='number',
        ),
        migrations.AddField(
            model_name='order',
            name='Date_of_order',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 4, 14, 10, 46, 0, 326965, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('date_of_return', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=20)),
                ('date_of_payment', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('amount', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.customer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.payment'),
        ),
    ]
