# Generated by Django 3.1.6 on 2021-04-14 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0016_auto_20210414_1046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Return',
            new_name='Replace',
        ),
    ]
