# Generated by Django 3.1.6 on 2021-04-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0018_auto_20210414_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='DRUGS', max_length=20),
        ),
    ]
